83 get providers and models from jsonrpc endpoint for validator settings
yeagerai/genlayer-simulator pull request #154
Opened 2024-05-14 17:20 UTC by bradleySuira

2024-05-14 21:57 UTC, cristiam86 requested changes

2024-05-15 01:35 UTC, bradleySuira commented on frontend/src/services/JsonRpcService.ts
> +import { rpcClient } from "@/utils";
got it so just map with methods and the method can put the string name of the rpcmethod

2024-05-15 02:04 UTC, bradleySuira commented on frontend/src/components/Simulator/NodeLogs.vue
> +      state.nodeLogs.push({ date: new Date().toISOString(), message: event.message})
in this case the message object form the event hast all the fields 

![Screenshot 2024-05-14 at 9 02 57 PM](https://github.com/yeagerai/genlayer-simulator/assets/1889891/e165f51f-56a5-448f-aba4-d9082cab0b12)

2024-05-15 02:04 UTC, bradleySuira commented on frontend/src/components/Simulator/NodeLogs.vue
> +      state.nodeLogs.push({ date: new Date().toISOString(), message: event.message})
so we keep all the data just in case we need to show them later

2024-05-15 07:22 UTC, cristiam86 approved these changes

2024-05-15 07:23 UTC, cristiam86 approved these changes

2024-05-15 09:13 UTC, merged