171 simulator   e2e frontend tests for contract examples
yeagerai/genlayer-simulator pull request #177
Opened 2024-05-22 14:28 UTC by bradleySuira

This includes the first version of e2e test with setup and first test
*How to test:*
- We should have all containers running  except the front end container
- run `nvm use && npm ci`
- run `nom run test:e2e`

2024-05-22 22:06 UTC, bradleySuira commented
<img width="1000" alt="Screenshot 2024-05-22 at 5 06 29 PM" src="https://github.com/yeagerai/genlayer-simulator/assets/1889891/dc493ce6-a85b-471c-9c54-6164ded4290f">
Updated with two examples

2024-05-23 10:29 UTC, cristiam86 commented
@bradleySuira please pull from main

2024-05-23 12:03 UTC, bradleySuira commented
it is up to date from main @cristiam86

2024-05-23 22:52 UTC, cristiam86 requested changes
small stuff

2024-05-23 22:52 UTC, cristiam86 commented on frontend/test/e2e/ContractExampleStorage.spec.ts
> +  it('should open Run debug page and set constructor arguments for WizardOfCoin', async () => {
@bradleySuira wrong contract name

2024-05-23 22:52 UTC, cristiam86 commented on frontend/test/e2e/ContractExampleStorage.spec.ts
> +  it('should call ask_for_coin() method', async () => {
@bradleySuira wrong method

2024-05-23 23:17 UTC, bradleySuira commented on frontend/test/e2e/ContractExampleStorage.spec.ts
> +  it('should open Run debug page and set constructor arguments for WizardOfCoin', async () => {
fixed

2024-05-23 23:18 UTC, bradleySuira commented on frontend/test/e2e/ContractExampleStorage.spec.ts
> +  it('should call ask_for_coin() method', async () => {
fixed

2024-05-24 07:24 UTC, cristiam86 approved these changes

2024-05-24 15:01 UTC, merged