86 genlayer simulator backend fixes
yeagerai/genlayer-simulator pull request #93
Opened 2024-04-29 23:29 UTC by sevenearths

Only one remaining is:

- The Contract state is mixing the input parameters and the self. should be updated an returned in the get_contract_state call

Please read [this comment](https://github.com/yeagerai/genlayer-simulator/issues/86#issuecomment-2083855120)

2024-05-01 09:15 UTC, sevenearths commented
> @sevenearths please update with main and adapt to the breaking changes from #92

Done!

2024-05-03 00:08 UTC, cristiam86 commented on rpc/server.py
> +    return_data['data'] = execution_output
```suggestion
    return_data['execution_output'] = execution_output
```
just to keep the format the same for now

2024-05-03 00:08 UTC, cristiam86 commented on genvm/server.py
> +@jsonrpc.method("deploy_contract")
why these methods appear as added if they are already in main just like that?

2024-05-03 00:09 UTC, cristiam86 requested changes
Please check the issues mentioned

2024-05-03 12:23 UTC, cristiam86 commented
Not needed anymore

2024-05-03 12:23 UTC, closed without merging